version: '3.9'

services: 
  django:
    build: .
    ports: 
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - sqlite

  sqlite:
    image: nouchka/sqlite3
    ports: 
      - "8191:8191"
    volumes:
      - sqlite_data:/sqlite

volumes:
  sqlite_data:
