# Generated by Django 5.1.6 on 2025-02-10 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateDOF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('currency_exchange', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
